spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:1000}
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.format_sql: true
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem://localhost/~/user;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 5
      auto-commit: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:22101/local_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 10
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        rewriteBatchedStatements: true
        allowPublicKeyRetrieval: true
        useSSL: false

logging.level.org.hibernate.type.descriptor.sql: trace    # ?에 어떤값이 있는지 노출
logging.level.org.springframework.web.filter: debug
